language: ruby
rvm:
- 2.2.1
deploy:
  api_key:
    secure: b52KLvX+99D2+KTN8O+cxSoriEQzi590JiQfd1Xq6xJ45EGbdoh1z3A8onoR2bAd5ViJotv8s+xztV4NvflwxQbW6B14STiDDs0E13jLOFywCTtF5tcDoWRU+nF6JaCG7xEWsJexT13sGJFBJRcWrhbAIACR8NA3QNeUvXHeGNRaZjvOBIPRENhz3yLRdNOS6Uhnldpl/l3dQy5s0XxmjtXc2MRfv2GdCNTHJ1HQ7S8I8crkM+6Xj2fUATjwpbLnVJbyfFOrJbwibO/LhtdwnemM2dx5TdjqSn5gBF1WxXa3Ms8D2WmZW08Du4xYiAimTWifkyY27hQ82nibsVSxKKSeF0NbmAvGADDbBd+dYJ/YeLYUuyiz1oiZqKtomqbsB3YtHQmTI9bDNTMrkh5kQJ/W8a3M6uMBVWzKCYzzSoFOZpzaymzW9YbgkQbpZWYiFfxcUI4o3T255CiewLfwd1EfVmJX3y8Ze/NKPIPIi9igodBaq9Fq8Uv6t/hnc7d2aqp76ixH9JOHZCFwJWwVKjhlenGnrqot2e0NSBB77XH4tJcHBdJKnqFrsJmBIr4nYTHmSi1Zk3O2i77VAaRYtZFMZdgFVLsJzZBrvy76mRT8YBnU2JEPu5wbGQ4lExW+z/aUte8nSniDb1kz1iizMqkI1A+8zeLoLnajEQkevp4=
