language: ruby
rvm:
- 2.2.1
deploy:
  provider: heroku
  api_key:
    secure: Zx4b/QDDF5efocJQhE5iawrl6Q2sWycJLl3teIRgCpdG1zOhexE1K15N4yVQ+WBRjND9PCZJSVwVXzbO8rZ2xvGRKwHz5aMGyt9JbO01yri7xurS+qDEuYh3Txo39aild98lEqwVVRxrPEjMBtrPDK/4B8UpM65CulkiKBiefYaNxD+w4PGsTL9/QOtpvx9lgDlr0EePQ7sMuqaWLgk5r6XlrqBD/t19tNVbg/hZWOoOC1yPN76jQGcLZeMcs/eS13jJZQ3sCov4G9aJH3ICD7k+tXAC65ocveQRbMtuLVa1sqdBOPq2p7DdCQvbBayXVAXstgXQAJchhA+Wygv9rgEFIdk1649W9HIOex9BANOuRWiHkAalgoaA5VBcB3/SKqc1faH1UVO48uB6gbJh0+nmREll6PTBUqt3kiKWlgT/Xi0dmqnAjsItZy8+J89QXQmZooZeJ90YPl9Ylre60ZQCCuOEfTSojKY8s66bXqOW0G/7gp9TvjXT2jyHK5YSgriFzTvDzoHKPucL3ZsJ+iLAL4KsTxi4GCkmVFiEQrUs9U49eb+yKQMi2qWA72UYD7yZVKBXw3tlpWxNi/8sFSF2Fajsm+kQOaWtaJCrARkwRrKNzq1J/unZzZxwJr+QIeZF05w9ftKIdMRSv7puVFBTCpP0KXh0iklGZCXCMtU=
  app: eternz
  on:
    repo: AbDaniel/eternz-rails
